# Generated by Django 3.0.5 on 2020-10-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20201029_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='age',
        ),
    ]
